version: "3.9"

services:
  db:
    image: postgres:15
    container_name: movie_db
    restart: always
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: movie_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: movie_app
    depends_on:
      - db
      - redis   # 🔥 IMPORTANT
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      DB_NAME: moviesdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app

volumes:
  pgdata: